version: "3.7"

services:
  database_blog:
    image: postgres
    container_name: database_blog
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog@158
      - POSTGRES_DB=blog
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local